# Dependabot Configuration for Mathematics.NET

version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "docs"
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: ".github/workflows"
  schedule:
    interval: daily
