// <copyright file="Prime.cs" company="Mathematics.NET">
// Mathematics.NET
// https://github.com/HamletTanyavong/Mathematics.NET
//
// MIT License
//
// Copyright (c) 2023-present Hamlet Tanyavong
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// </copyright>

// TODO: Implement the Sieve Of Atkin: <see href="https://www.ams.org/journals/mcom/2004-73-246/S0025-5718-03-01501-1/S0025-5718-03-01501-1.pdf"><i>Prime Sieves Using Binary Quadratic Forms</i></see> by A. O. L. Atkin and D. J. Bernstein.

#pragma warning disable IDE0305

using System.Collections;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Mathematics.NET.NumberTheory;

/// <summary>Provides methods for working with prime numbers.</summary>
public static class Prime
{
    private record struct PrimeIndex
    {
        public int Prime;
        public int Index;
    }

    private static ImmutableList<int> s_increments = [4, 2, 4, 2, 4, 6, 2, 6];

    /// <summary>An upper bound to the prime counting function.</summary>
    /// <remarks>
    /// The inequality used is
    /// <code>
    /// pi(x) &lt; 1.25506 * x / ln(x) for x > 1.
    /// </code>
    /// See <see href="https://projecteuclid.org/journalArticle/Download?urlId=10.1215%2Fijm%2F1255631807"><i>Approximate Formulas for Some Functions of Prime Numbers</i></see> by J. Barkley Rosser and Lowell Schoenfeld.
    /// </remarks>
    /// <param name="limit">The limit.</param>
    /// <returns>An upper bound to the number of prime numbers less than <paramref name="limit"/>.</returns>
    public static Real CountingFunctionUpperBound(Real limit)
        => limit / Real.Ln(limit) * 1.22506;

    /// <summary>Use the Sieve of Eratosthenses to generate primes below a certain limit.</summary>
    /// <param name="wheel">A wheel generated by the first n primes.</param>
    /// <param name="limit">The limit.</param>
    /// <returns>A list of primes.</returns>
    public static IEnumerable<int> SieveOfEratosthenes(Wheel<int> wheel, int limit)
    {
        if (limit < 2)
            yield break;

        foreach (var prime in wheel.Basis)
        {
            if (prime <= limit)
                yield return prime;
        }

        BitArray array = new(limit - 1);
        var bound = (int)Math.Floor(Math.Sqrt(limit));

        foreach (var candidate in wheel.Spin().TakeWhile(x => x <= limit))
        {
            if (candidate <= bound)
            {
                if (!array[candidate - 2])
                {
                    yield return candidate;
                    var j = candidate * candidate;
                    while (j > 0 && j <= limit)
                    {
                        array[j - 2] = true;
                        j += candidate;
                    }
                }
            }
            else
            {
                if (!array[candidate - 2])
                    yield return candidate;
            }
        }
    }

    /// <summary>Use the Sieve of Eratosthenes with a <paramref name="wheel"/> to generate prime numbers lazily.</summary>
    /// <remarks>See <see href="https://www.cambridge.org/core/journals/journal-of-functional-programming/article/genuine-sieve-of-eratosthenes/FD3E90871269020CA6C64C25AB8A4FBD"><i>The Genuine Sieve of Eratosthenes</i></see> by Melissa E. O'Neill.</remarks>
    /// <param name="wheel">A wheel generated by the first n primes.</param>
    /// <returns>Prime numbers in a sequence.</returns>
    [Experimental("NUM0001", UrlFormat = "https://mathematics.hamlettanyavong.com/diagnostic-messages/experimental/num0001")]
    public static IEnumerable<int> SieveOfEratosthenes(Wheel<int> wheel)
    {
        foreach (var prime in wheel.Basis)
        {
            yield return prime;
        }

        // Consider letting the initial capacity be user-specified.
        PriorityQueue<PrimeIndex, long> queue = new(128);

        long priority;
        int i = 1;

        foreach (var candidate in wheel.Spin())
        {
            // Remove composites.
            while (queue.TryPeek(out var _, out priority) && priority < candidate)
            {
                Adjust(wheel, queue);
            }

            if (queue.TryPeek(out var _, out priority) && priority == candidate)
            {
                Adjust(wheel, queue);
            }
            else
            {
                yield return candidate; // The candidate is prime.
                priority = (long)candidate * candidate;
                PrimeIndex multiple = new() { Prime = candidate, Index = i };
                queue.Enqueue(multiple, priority);
            }

            i++;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static void Adjust(Wheel<int> wheel, PriorityQueue<PrimeIndex, long> queue)
        {
            var current = queue.Dequeue();
            PrimeIndex next = current with { Index = current.Index + 1 };
            queue.Enqueue(next, current.Prime * wheel[current.Index]);
        }
    }

    /// <summary>Find the prime factors of a number.</summary>
    /// <param name="n">The number.</param>
    /// <returns>A list of factors.</returns>
    public static ImmutableList<int> Factor(int n)
    {
        List<int> factors = [];

        while (n % 2 == 0)
        {
            factors.Add(2);
            n /= 2;
        }
        while (n % 3 == 0)
        {
            factors.Add(3);
            n /= 3;
        }
        while (n % 5 == 0)
        {
            factors.Add(5);
            n /= 5;
        }

        var i = 0;
        var j = 7;
        while (j * j <= n)
        {
            if (n % j == 0)
            {
                factors.Add(j);
                n /= j;
            }
            else
            {
                j += s_increments[i];
                if (i < 7)
                    i++;
                else
                    i = 0;
            }
        }

        if (n > 1)
            factors.Add(n);

        return factors.ToImmutableList();
    }

    /// <inheritdoc cref="Factor(int)"/>
    public static ImmutableList<long> Factor(long n)
    {
        List<long> factors = [];

        while (n % 2 == 0)
        {
            factors.Add(2);
            n /= 2;
        }
        while (n % 3 == 0)
        {
            factors.Add(3);
            n /= 3;
        }
        while (n % 5 == 0)
        {
            factors.Add(5);
            n /= 5;
        }

        var i = 0;
        var j = 7;
        while (j * j <= n)
        {
            if (n % j == 0)
            {
                factors.Add(j);
                n /= j;
            }
            else
            {
                j += s_increments[i];
                if (i < 7)
                    i++;
                else
                    i = 0;
            }
        }

        if (n > 1)
            factors.Add(n);

        return factors.ToImmutableList();
    }
}
