// <copyright file="Wheel.cs" company="Mathematics.NET">
// Mathematics.NET
// https://github.com/HamletTanyavong/Mathematics.NET
//
// MIT License
//
// Copyright (c) 2023-present Hamlet Tanyavong
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// </copyright>

using System.Numerics;

namespace Mathematics.NET.NumberTheory;

/// <summary>A base class for wheels used in factorization.</summary>
/// <typeparam name="T">A type that implements <see cref="IBinaryInteger{TSelf}"/>.</typeparam>
public abstract class Wheel<T>
    where T : IBinaryInteger<T>
{
    public Wheel() { }

    /// <summary>The prime numbers used to form the basis for the wheel.</summary>
    public abstract T[] Basis { get; }

    /// <summary>The spokes of the wheel—numbers that are coprime with the basis.</summary>
    public abstract T[] Spokes { get; }

    /// <summary>Increments between the spokes of the wheel.</summary>
    public abstract T[] Increments { get; }

    /// <summary>The size of the wheel.</summary>
    public abstract T Size { get; }

    /// <summary>The number of spokes on the wheel.</summary>
    public abstract int SpokeCount { get; }

    /// <summary>The number of spoke increments on the wheel.</summary>
    public abstract int IncrementCount { get; }

    /// <summary>Get the next number generated by the wheel.</summary>
    /// <returns>The next number.</returns>
    public abstract IEnumerable<T> Spin();

    /// <summary>Get the <paramref name="i"/>th element of the wheel.</summary>
    /// <param name="i">The index.</param>
    /// <returns>The element.</returns>
    public abstract T this[int i] { get; }
}
