// <copyright file="Wheel.cs" company="Mathematics.NET">
// Mathematics.NET
// https://github.com/HamletTanyavong/Mathematics.NET
//
// MIT License
//
// Copyright (c) 2023-present Hamlet Tanyavong
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// </copyright>

#pragma warning disable IDE0290

using System.Collections.Immutable;
using System.Numerics;

namespace Mathematics.NET.NumberTheory;

/// <summary>A base class for wheels used in factorization.</summary>
/// <typeparam name="T">A type that implements <see cref="IBinaryInteger{TSelf}"/>.</typeparam>
public abstract class Wheel<T>
    where T : IBinaryInteger<T>
{
    private protected readonly ImmutableList<T> _basis;
    private protected readonly ImmutableList<T> _spokes;
    private protected readonly ImmutableList<T> _increments;

    public Wheel(List<T> basis, List<T> spokes, List<T> increments)
    {
        _basis = [.. basis];
        _spokes = [.. spokes];
        _increments = [.. increments];

        Size = basis.Aggregate((x, y) => x * y);
    }

    /// <summary>The prime numbers used to form the basis for the wheel.</summary>
    public ImmutableList<T> Basis => _basis;

    /// <summary>The spokes of the wheel—numbers that are coprime with the basis.</summary>
    public ImmutableList<T> Spokes => _spokes;

    /// <summary>Increments between the spokes of the wheel.</summary>
    public ImmutableList<T> Increments => _increments;

    /// <summary>The size of the wheel.</summary>
    public T Size { get; }

    /// <summary>The number of spokes on the wheel.</summary>
    public int SpokeCount => _spokes.Count;

    /// <summary>The number of spoke increments on the wheel.</summary>
    public int IncrementCount => _increments.Count;

    /// <summary>Get the next number generated by the wheel.</summary>
    /// <returns>The next number.</returns>
    public virtual IEnumerable<T> Spin()
    {
        var value = _spokes[0];
        yield return value;

        for (int i = 0; (value += _increments[i]) > T.Zero; i = i < _increments.Count - 1 ? i + 1 : 0)
        {
            yield return value;
        }
    }

    /// <summary>Get the <paramref name="i"/>th element of the wheel.</summary>
    /// <param name="i">The index.</param>
    /// <returns>The element.</returns>
    public abstract T this[int i] { get; }
}
