# Check that the only branch that can merge to "main" is "dev"

name: "Check Incoming Branch"

on:
  pull_request:
    branches:
    - main

jobs:
  check-branch:
    name: Check Incoming Branch
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Branch
        run: echo "Current branch is ${{ github.head_ref }}"
        id: current-branch

      - name: Validate Branch
        run: |
          if [ '${{ steps.current-branch.outputs.branch }}' == 'dev' ]; then
            echo "Valid incoming branch"
            exit 0
          else
            echo "ERROR: Can only merge to 'main' branch from 'dev' branch"
            exit 1
          fi
